### ISSUE TITLE
vscode编译后，执行spring-restful-api-3.0.jar报错“no main manifest attribute”

### ISSUE THREAD

**Issue by liujitao** [thousmile/spring-admin-vue#20]
![2022-04-15_15-41](https://user-images.githubusercontent.com/1335460/163541202-18ae045f-fdd1-4092-9406-18a1064e1b9e.png)
![2022-04-15_15-41_1](https://user-images.githubusercontent.com/1335460/163541218-d19da32a-c79c-4b92-989b-165afa21dd34.png)
![2022-04-15_15-42](https://user-images.githubusercontent.com/1335460/163541224-39f3a585-1b8b-4d6d-8c76-218dd5f8d685.png)
![2022-04-15_15-42_1](https://user-images.githubusercontent.com/1335460/163541230-45c1e684-a4cc-461d-94d9-fe44c7635840.png)

**Comment by thousmile** [comment]
已经解决了！
